import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
WEB_DIR = os.path.abspath(os.path.join(SCRIPT_DIR, "..", "interfata_web"))

ASSETS = {
    "index_html": "index.html",
    "control_html": "control.html",
    "delay_html": "delay.html",
    "distors_html": "distors.html",
    "reverb_html": "reverb.html",
    "script_js": os.path.join("js", "script.js"),
    "stil_css": os.path.join("css", "stil.css"),
    "audio_delay": os.path.join("audio", "delay.ogg"),
    "audio_distors": os.path.join("audio", "distors.ogg"),
    "audio_reverb": os.path.join("audio", "reverb.ogg"),
    "img_github": os.path.join("imagini", "github.png"),
    "img_raspberry": os.path.join("imagini", "raspberry.png"),
    "img_favicon": os.path.join("imagini", "favicon.ico"),
}

def generate_header(output_path):
    with open(output_path, "w", encoding="utf-8") as out:
        out.write("/* Automatically generated by generate_assets.py - DO NOT EDIT */\n")
        out.write("#ifndef GENERATED_ASSETS_H\n")
        out.write("#define GENERATED_ASSETS_H\n\n")

        for var_name, relative_path in ASSETS.items():
            file_path = os.path.join(WEB_DIR, relative_path) if "../interfata_web" not in relative_path else relative_path
            
            if not os.path.exists(file_path):
                print(f"Warning: File {file_path} not found. Skipping.")
                continue
                
            with open(file_path, "rb") as f:
                data = f.read()
            
            # Write out data as a static const byte array
            out.write(f"static const unsigned char asset_{var_name}[] = {{\n    ")
            
            # Format bytes to hex (0x00, 0x01...) format
            hex_bytes = [f"0x{b:02x}" for b in data]
            
            # Break down lines every 12 bytes for readability
            for i in range(0, len(hex_bytes), 12):
                out.write(", ".join(hex_bytes[i:i+12]) + ",\n    ")
                
            out.write("\n};\n")
            out.write(f"static const unsigned int asset_{var_name}_len = {len(data)};\n\n")

        out.write("#endif /* GENERATED_ASSETS_H */\n")

if __name__ == "__main__":
    # If CMake passes an explicit path, use it, otherwise generate locally
    output = sys.argv[1] if len(sys.argv) > 1 else "generated_assets.h"
    generate_header(output)
    print(f"Successfully generated {output}")